
import com.sun.glass.events.KeyEvent;
import java.awt.Frame;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammad Ali
 */
public class NewJFrame2 extends javax.swing.JFrame {
    int countp=0;
    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        File filee = new File("File\\G_income.txt"); 
            
            BufferedReader brp; 
        try {
            brp = new BufferedReader(new FileReader(filee));
            String stt; 
            
            try {
                while ((stt = brp.readLine()) != null)
                {   countp++;
                    System.out.println(stt);
                }
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(countp==0){
        countp++;
        }
        System.out.println(countp);
        
        
        
        
        //////////////**********Show total amount on label***********/////////////
        
        FileReader file;
        int phy = 0;
        int current_amount;
        try {
            file = new FileReader("File\\TotalAmount.txt");
            BufferedReader bf= new BufferedReader(file);
            String st = bf.readLine();
            int sum=0;
            int count=0;
        while((st=bf.readLine())!=null){
          
            StringTokenizer stn = new StringTokenizer(st);
            phy=Integer.parseInt(stn.nextToken());
            label5.setText(st);
            sum=sum+phy;
            count++;
            System.out.printf("Total Amount=%d\n", sum);
            System.out.println("--------------------------------------------------------------------------");
            
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gamount = new javax.swing.JTextField();
        gdes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("View record");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Enter G. donation Amount : ");

        gamount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamountActionPerformed(evt);
            }
        });
        gamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gamountKeyPressed(evt);
            }
        });

        gdes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gdesKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Description :");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Dummy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Total Amount : ");

        label5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\pic\\lnp.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gdes, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(gamount)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gamount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gdes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        NewJFrame1 nf1=new NewJFrame1();
        nf1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        
        FileReader file;
        int phy = 0;
        int current_amount;
        try {
            file = new FileReader("File\\TotalAmount.txt");
            BufferedReader bf= new BufferedReader(file);
            String st = bf.readLine();
            int sum=0;
            int count=0;
        while((st=bf.readLine())!=null){
          
            StringTokenizer stn = new StringTokenizer(st);
            phy=Integer.parseInt(stn.nextToken());
            sum=sum+phy;
            count++;
            System.out.printf("Total Amount=%d\n", sum);
            System.out.println("--------------------------------------------------------------------------");
            
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        /////////////////////////////////////////////////Test/////////////////
        ///////////////////////////////////////////////////////////////
        ///////////////////////////////////////////////////
        String gen_amount=gamount.getText();
        String gen_description=gdes.getText();
        ////////////////////////////////////////////////////////////Writing data into file///////////////////////////////////
        String fileContent =" , "+gen_amount;
        String val2=" , "+gen_description;
        String count_val=Integer.toString(countp);
        String val3=count_val;
        
        current_amount=Integer.parseInt(gen_amount);
        current_amount=current_amount+phy;
        System.out.println("\t"+current_amount);
        String str1 = Integer.toString(current_amount);
        String str2="Total_Amount";
        
        BufferedWriter writer;
        try {
            writer = new BufferedWriter(new FileWriter("File\\G_income.txt",true));
                            ////////////////amount write///////////////////////
            writer.newLine();
            writer.write(val3);
            writer.write(fileContent);
            //writer.newLine();
                            ////////////////Description write//////////
            writer.write(val2);
            //writer.newLine();
            
            
            //writer.newLine();
            writer.close();
            
            BufferedWriter wr;
            wr = new BufferedWriter(new FileWriter("File\\TotalAmount.txt"));
            wr.write(str2);
            wr.newLine();
            wr.write(str1);
            wr.close();
            javax.swing.JOptionPane.showMessageDialog(rootPane,"Sucessfully enter");
            gamount.setText("");
            gdes.setText("");
            countp++;
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(rootPane,"Error");
        }
        ////////////////*********************************//////////////////////////
        




        FileReader file1;
        int phy1 = 0;
        int current_amount1;
        try {
            file = new FileReader("File\\TotalAmount.txt");
            BufferedReader bf= new BufferedReader(file);
            String st = bf.readLine();
            int sum=0;
            int count=0;
        while((st=bf.readLine())!=null){
          
            StringTokenizer stn = new StringTokenizer(st);
            phy1=Integer.parseInt(stn.nextToken());
            sum=sum+phy;
            label5.setText(st);
            count++;
            System.out.printf("Total Amount=%d\n", sum);
            System.out.println("--------------------------------------------------------------------------");
            
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        update up=new update();
        up.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        table tb=new table();
        tb.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void gamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gamountKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            gdes.requestFocus();
        }
    }//GEN-LAST:event_gamountKeyPressed

    private void gamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gamountActionPerformed

    private void gdesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdesKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()==KeyEvent.VK_ENTER){
       FileReader file;
        int phy = 0;
        int current_amount;
        try {
            file = new FileReader("File\\TotalAmount.txt");
            BufferedReader bf= new BufferedReader(file);
            String st = bf.readLine();
            int sum=0;
            int count=0;
        while((st=bf.readLine())!=null){
          
            StringTokenizer stn = new StringTokenizer(st);
            phy=Integer.parseInt(stn.nextToken());
            sum=sum+phy;
            count++;
            System.out.printf("Total Amount=%d\n", sum);
            System.out.println("--------------------------------------------------------------------------");
            
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        /////////////////////////////////////////////////Test/////////////////
        ///////////////////////////////////////////////////////////////
        ///////////////////////////////////////////////////
        String gen_amount=gamount.getText();
        String gen_description=gdes.getText();
        ////////////////////////////////////////////////////////////Writing data into file///////////////////////////////////
        String fileContent =" , "+gen_amount;
        String val2=" , "+gen_description;
        String count_val=Integer.toString(countp);
        String val3=count_val;
        
        current_amount=Integer.parseInt(gen_amount);
        current_amount=current_amount+phy;
        System.out.println("\t"+current_amount);
        String str1 = Integer.toString(current_amount);
        String str2="Total_Amount";
        
        BufferedWriter writer;
        try {
            writer = new BufferedWriter(new FileWriter("File\\G_income.txt",true));
                            ////////////////amount write///////////////////////
            writer.newLine();
            writer.write(val3);
            writer.write(fileContent);
            //writer.newLine();
                            ////////////////Description write//////////
            writer.write(val2);
            //writer.newLine();
            
            
            //writer.newLine();
            writer.close();
            
            BufferedWriter wr;
            wr = new BufferedWriter(new FileWriter("File\\TotalAmount.txt"));
            wr.write(str2);
            wr.newLine();
            wr.write(str1);
            wr.close();
            javax.swing.JOptionPane.showMessageDialog(rootPane,"Sucessfully enter");
            gamount.setText("");
            gdes.setText("");
            countp++;
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(rootPane,"Error");
        }
        ////////////////*********************************//////////////////////////
        




        FileReader file1;
        int phy1 = 0;
        int current_amount1;
        try {
            file = new FileReader("File\\TotalAmount.txt");
            BufferedReader bf= new BufferedReader(file);
            String st = bf.readLine();
            int sum=0;
            int count=0;
        while((st=bf.readLine())!=null){
          
            StringTokenizer stn = new StringTokenizer(st);
            phy1=Integer.parseInt(stn.nextToken());
            sum=sum+phy;
            label5.setText(st);
            count++;
            System.out.printf("Total Amount=%d\n", sum);
            System.out.println("--------------------------------------------------------------------------");
            
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          }
    }//GEN-LAST:event_gdesKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gamount;
    private javax.swing.JTextField gdes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label5;
    // End of variables declaration//GEN-END:variables
}
